[FEATURE] Add support for OPENSEARCH_JAVA_HOME (#128)
* [FEATURE] Add support for OPENSEARCH_JAVA_HOME

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

* Simplified condition checks

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

* Changing JAVA_HOME ->  condition

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

diff --git a/pa_bin/performance-analyzer-agent b/pa_bin/performance-analyzer-agent
--- a/pa_bin/performance-analyzer-agent
+++ b/pa_bin/performance-analyzer-agent
@@ -14,14 +14,19 @@ else
     OPENSEARCH_HOME=$1
 fi
 
-if [ -z "$2" ]; then
-    if [ -z "$JAVA_HOME" ]; then
-        echo "JAVA_HOME needs to be set or passed in as the second parameter."
-        exit 1
-    fi
-else
-    JAVA_HOME=$2
+if [ ! -z "$2" ]; then
+  JAVA_HOME=$2
+elif [ ! -z "$OPENSEARCH_JAVA_HOME" ]; then
+  # Use OPENSEARCH_JAVA_HOME if present
+  JAVA_HOME=$OPENSEARCH_JAVA_HOME
+elif [ -z "$JAVA_HOME" ]; then
+  # Nor OPENSEARCH_JAVA_HOME nor JAVA_HOME is present, failing 
+  echo "OPENSEARCH_JAVA_HOME / JAVA_HOME needs to be set or passed in as the second parameter."
+  exit 1
 fi
+
+echo "Using JAVA_HOME: $JAVA_HOME"
+export JAVA_HOME=$JAVA_HOME
 
 if ! echo $* | grep -E '(^-d |-d$| -d |--daemonize$|--daemonize )' > /dev/null; then
     export JAVA_OPTS=-Dopensearch.path.home=$OPENSEARCH_HOME\ -Dlog4j.configurationFile=$OPENSEARCH_HOME/performance-analyzer-rca/pa_config/log4j2.xml\ -XX:+ExitOnOutOfMemoryError
